backend:
  name: github
  repo: keithporcaro/staticlist # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
- label: "Project"
  name: "project"
  folder: "projects"
  create: true
  fields:
    - {label: "Name", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}